**1. Kaggle Dataset**

In [1]:
%pip install kagglehub

Collecting kagglehub
  Using cached kagglehub-0.3.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from kagglehub) (25.0)
Collecting pyyaml (from kagglehub)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting requests (from kagglehub)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm (from kagglehub)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting charset_normalizer<4,>=2 (from requests->kagglehub)
  Using cached charset_normalizer-3.4.4-cp313-cp313-macosx_10_13_universal2.whl.metadata (37 kB)
Collecting idna<4,>=2.5 (from requests->kagglehub)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests->kagglehub)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->kagglehub)
  Using cached certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Using cached kagglehub-0.3.13-py3-none-any.whl (68 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp313-cp313-macosx_10_13_universal2.whl (208 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: urllib3, tqdm, pyyaml, idna, charset_normalizer, certifi, requests, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [kagglehub]/8 [kagglehub]
Successfully installed certifi-2025.11.12 charset_normalizer-3.4.4 idna-3.11 kagglehub-0.3.13 pyyaml-6.0.3 requests-2.32.5 tqdm-4.67.1 urllib3-2.5.0

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import os

os.environ["KAGGLE_API_TOKEN"] = ""

Dataset 1 link: https://www.kaggle.com/datasets/alessandrolobello/the-ultimate-earthquake-dataset-from-1990-2023

Dataset 2 link: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

In [3]:
import kagglehub

# Download latest version
# path = kagglehub.dataset_download("alessandrolobello/the-ultimate-earthquake-dataset-from-1990-2023")
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

/Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/sid/.cache/kagglehub/datasets/uciml/pima-indians-diabetes-database/versions/1

In [ ]:
# uncomment below lines to connect google drive to this notebook and save the dataset there
# from google.colab import drive
# drive.mount('/content/drive')

In [4]:
import shutil

# copy the dataset from source dir to destination dir
# shutil.copytree(
#     "/kaggle/input/the-ultimate-earthquake-dataset-from-1990-2023",
#     "/content/dataset",
#     dirs_exist_ok=True
# )

shutil.copytree(
    "/Users/sid/.cache/kagglehub/datasets/uciml/pima-indians-diabetes-database/versions/1",
    "/Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/7_4_load_kaggle_uci_datasets/datasets",
    dirs_exist_ok=True
)

'/Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/7_4_load_kaggle_uci_datasets/datasets'

In [5]:
import pandas as pd

In [7]:
# df = pd.read_csv("/content/dataset/Eartquakes-1990-2023.csv")
df = pd.read_csv("/Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/7_4_load_kaggle_uci_datasets/datasets/diabetes.csv")

In [8]:
df.shape

(768, 9)

In [9]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

**2. UCI ML Repository Datasets**

In [10]:
%pip install ucimlrepo

Collecting ucimlrepo
  Using cached ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from ucimlrepo) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sid/Documents/0_udemy_backup/2_udemy_ml_course_backup/2_ml_course/udemy-2-ml-course-rec-code/section_7_data_collection/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Using cached ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [12]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is one of the earliest datasets used in the literature on classification methods and widely used in statistics and machine learning.  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is linearly separable from the other 2; the latter are not linearly separable from each other.\n\nPredicted attribute: class of iris plant.\n\nThis is an exceedingly simple domain.\n\nThis data differs from the data presented in Fishers article (identified by Steve Chadwick,  spchadwick@espeedaz.net ).  The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.  ', 'purpose': 'N/A', 'funded_by': None, 'instances_represent': 'Each instance is a plant', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
           name     role         type demographic  \
0  sepal length  Feature   Continuous        None
1   sepal width  Feature   Continuous        None
2  petal length  Feature   Continuous        None
3   petal width  Feature   Continuous        None
4         class   Target  Categorical        None

                                         description units missing_values
0                                               None    cm             no
1                                               None    cm             no
2                                               None    cm             no
3                                               None    cm             no
4  class of iris plant: Iris Setosa, Iris Versico...  None             no

In [13]:
print(type(X))

<class 'pandas.core.frame.DataFrame'>

In [14]:
X.head()

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [15]:
y.head()

         class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa